pipeline:
    build:
        image: debian
        commands:
            - apt update
            - apt install -y cmake clang perl zlib1g-dev libssl-dev
            - cmake .
            - cmake --build .
            - ctest
