version: 1.0.{build}
branches:
  only:
  - master
os: Visual Studio 2013
configuration: Release
platform: x64
clone_folder: C:\projects\neon-lang\
install:
- ps: >-
    if (-not (Test-Path C:\Python27)){
      Start-FileDownload "https://www.python.org/ftp/python/2.7.9/python-2.7.9.amd64.msi" -FileName python-2.7.9.amd64.msi
      Start-Process "python-2.7.9.amd64.msi" -ArgumentList "/quiet" -Wait
    }
- ps: >-
    if (-not (Test-Path C:\Python27\Lib\site-packages\scons-2.4.1)){
      Start-FileDownload "http://downloads.sourceforge.net/project/scons/scons/2.4.1/scons-2.4.1.zip" -FileName "scons-2.4.1.zip"
      7z x -y scons-2.4.1.zip
      New-Item C:\SCons -ItemType Directory
      Move-Item .\scons-2.4.1 C:\SCons\scons-2.4.1
      Start-Process "python.exe" -ArgumentList "c:\SCons\scons-2.4.1\setup.py" -Wait
    }
cache:
- C:\projects\neon-lang
build_script:
- cmd: CD C:\projects\neon-lang
- cmd: C:\Python27\python.exe C:\Python27\Scripts\scons.py --directory=c:\projects\neon-lang
