image: fedora/latest
packages:
- g++
- cmake
- ncurses
- gmp-devel
- zlib-devel
- openssl-devel
sources:
- https://git.sr.ht/~ghewgill/neon-lang
triggers:
- action: email
  condition: failure
  to: ~ghewgill/neon-builds@lists.sr.ht
tasks:
- prep: |
    cd neon-lang
    git submodule deinit .
- build: |
    cd neon-lang
    cmake .
    cmake --build .
- test: |
    cd neon-lang
    echo NOT RUNNING: ctest
