name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prep
      run: cmake .
    - name: build
      run: cmake --build .
    - name: test
      run: ctest --output-on-failure
